### ISSUE TITLE
Higher resolution g-files

### ISSUE THREAD

**Issue by rmchurch** [cfs-energy/SPARCPublic#1]
Would it be possible to generate g-files with resolution of 513x513? I looked to do this with FreeGS, but the SPARC machine isn't defined in its machine.py file, which seems to be required for reading the file into freegs to modify.

**Comment by cfs-akuang** [comment]
A new file has been uploaded that should be a high resolution grid as requested.

main/PrimaryReferenceDischarge/SPARC_DN_PRD_freegs_513_20221206
